### ISSUE TITLE
Tag versions as proper releases

### ISSUE THREAD

**Issue by peterhoeg** [arcage/crystal-email#74]
For versions < 0.7, all releases in this repo are tagged as pre-releases, which means our nix tooling isn't able to fetch the tarballs. Is there any chance at the very least that 0.6.4 can be tagged as a proper release?

We can (and should) work around this fact in our crystal tooling on nix, but that's a separate issue.

**Comment by peterhoeg** [comment]
Just in case somebody else has the same problem. The workaround is to use `shard.override.yml` and specify the commit of the version:
```yml
---
dependencies:
  email:
    github: arcage/crystal-email
    commit: 3899a238d58ec5ef3fd117d8d47bf122abd8f5c3
```
